In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/workspace/datasets/train.csv")

In [3]:
df.head()

,user,sku,category,query,click_time,query_time
0,000000df17cd56a5df4a94074e133c9d4739fae3,2125233,abcat0101001,Televisiones Panasonic 50 pulgadas,2011-09-01 23:44:52.533,2011-09-01 23:43:59.752
1,000001928162247ffaf63185cd8b2a244c78e7c6,2009324,abcat0101001,Sharp,2011-09-05 12:25:37.42,2011-09-05 12:25:01.187
2,000017f79c2b5da56721f22f9fdd726b13daf8e8,1517163,pcmcat193100050014,nook,2011-08-24 12:56:58.91,2011-08-24 12:55:13.012
3,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877125,abcat0101001,rca,2011-10-25 07:18:14.722,2011-10-25 07:16:51.759
4,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877134,abcat0101005,rca,2011-10-25 07:19:51.697,2011-10-25 07:16:51.759

In [5]:
gb = df.groupby("query")
gb.first()

,user,sku,category,click_time,query_time
query,,,,,
!pod,ee0c57592de376bf9e687eaab46c05f6d8e15988,9084206,pcmcat144700050004,2011-10-16 22:22:01.996,2011-10-16 22:21:11.988
#,0240c3e637c81f402565ce97978c032b2f6454f3,1972308,cat02010,2011-10-25 23:46:17.884,2011-10-25 23:43:48.686
# 1 hits of the 50s,22ee0cd6a6dce1df2f5487ed6a6faa6b78c8fb06,17072944,cat02010,2011-09-07 18:43:00.204,2011-09-07 18:42:38.189
# TC-P50GT30,144d310cedd839dc33d5dddc8847b90a1347b048,2025359,abcat0102003,2011-09-26 02:16:49.572,2011-09-26 02:12:28.204
#1 Girl,e9fbedbfa8d6d3309b00871185a73aa40019321c,3486349,cat02009,2011-09-20 14:20:15.77,2011-09-20 14:19:59.599
...,...,...,...,...,...
��Mfr: SONY ��Model: VPCYB/15KX/P �� ��UPC: 027242819757,1b4cd9dccc522a5aa0ef1e146c5277ce704c821e,1945531,pcmcat209000050007,2011-10-04 18:17:43.862,2011-10-04 18:15:27.714
��Mfr: TOSHIBA ��Model: BDX4200 ��,28e001b8f0605e7b3a2eac7ec21c80ea10af3488,2114042,abcat0102003,2011-09-24 11:14:53.634,2011-09-24 11:14:42.439
��Model: U30JCB2B,d512aff4d504f12273f069830226aac45ed8b432,3104033,pcmcat247400050000,2011-10-08 05:22:29.851,2011-10-08 05:17:54.345
����Mfr: SONY��Model: DSCW530/B ��,3a7e036989a666d101d77d29cdcf9405c4e5261c,2507506,abcat0401004,2011-10-04 11:20:10.006,2011-10-04 11:19:25.816
����� HP DV5-2074DX 14.5in Laptop i3 2.13GHz 3GB 250GB DVDRW,bab6934c3681408ba248bc25ac60f358d0112afe,2660188,pcmcat247400050000,2011-08-21 01:33:36.149,2011-08-21 01:31:06.28

In [6]:
gb.get_group("ipad").count()

user          5036
sku           5036
category      5036
query         5036
click_time    5036
query_time    5036
dtype: int64

In [7]:
df[df["category"] == "abcat0101001"]

,user,sku,category,query,click_time,query_time
0,000000df17cd56a5df4a94074e133c9d4739fae3,2125233,abcat0101001,Televisiones Panasonic 50 pulgadas,2011-09-01 23:44:52.533,2011-09-01 23:43:59.752
1,000001928162247ffaf63185cd8b2a244c78e7c6,2009324,abcat0101001,Sharp,2011-09-05 12:25:37.42,2011-09-05 12:25:01.187
3,000017f79c2b5da56721f22f9fdd726b13daf8e8,2877125,abcat0101001,rca,2011-10-25 07:18:14.722,2011-10-25 07:16:51.759
19,0000c4e9d7075985d1020c456e7ce36f83f834eb,2126065,abcat0101001,Samsung 40,2011-09-28 17:27:11.184,2011-09-28 17:26:15.832
40,00017f7beeac02736c0ce7bf1e75f3010939b34e,1831054,abcat0101001,lcd tv,2011-09-28 07:26:32.153,2011-09-28 07:26:21.476
...,...,...,...,...,...,...
1865071,fff7afecf87f8043ce4b4fcbd8ed47d7ffd52679,2620821,abcat0101001,lcd tv,2011-10-16 11:13:30.233,2011-10-16 11:13:25.858
1865077,fff7edfacf2c376fa8ea4f637c33013d057ae70a,1854328,abcat0101001,goldeneye movie,2011-09-20 18:25:30.494,2011-09-20 18:25:16.548
1865119,fff97c95234212c39d6f04c9854fa94d94bc0cce,1854819,abcat0101001,2622037 2127204 2127213 2121716 2138291,2011-10-08 07:00:01.108,2011-10-08 06:56:16.829
1865190,fffc750c85c62fe732b8223d5872be6e0fc03593,2262074,abcat0101001,Pn51d8000,2011-10-24 18:15:10.27,2011-10-24 18:15:05.628
1865224,fffd4ebf04febc87ca4b34c730c78d7bf1bef564,2620821,abcat0101001,Infinity,2011-10-19 21:20:40.308,2011-10-19 21:20:15.504

In [8]:
df.sample(n=100)

,user,sku,category,query,click_time,query_time
1171919,a0dd4a85f277fcd0e6d19e979698c3370223989a,8216487,abcat0506002,pc2100,2011-10-20 00:03:46.052,2011-10-20 00:03:30.255
1371868,bc592ede77209ebb76bbddcb6b5ec26f3e86d9dc,1947053,abcat0908002,dehumidifier,2011-10-06 23:16:53.666,2011-10-06 23:16:44.939
1845318,fd42594ec38dfa9dd59a322c9d2f01351ba2a563,2817255,pcmcat247400050000,2371074 2126339 2126108,2011-10-22 20:19:42.584,2011-10-22 20:18:34.297
240363,21203dffd534459ce603640662925ca499b9b2cd,2265381,pcmcat209000050008,Blackberry tablet,2011-10-20 10:24:48.626,2011-10-20 10:24:33.249
831421,725e9d3de05d49549f33e6b26393f6b7a90a7ba3,9926019,pcmcat234200050001,Olympus pen,2011-09-19 12:46:14.702,2011-09-19 12:44:33.157
...,...,...,...,...,...,...
135207,12a89c80d3b1399d6c0b1af497746b16e2fdd8c3,5431927,abcat0515040,microphones,2011-10-19 22:07:18.239,2011-10-19 22:06:14.421
916164,7df7a3c1921f6fa553f8a42499955fc63ef1a437,2525772,abcat0410021,37mm lens filter,2011-08-31 10:26:09.504,2011-08-31 10:23:26.039
224653,1f072b7c3b3236a90e7b9e22a577092e69234b06,1945531,pcmcat209000050007,ipad,2011-10-18 13:42:18.704,2011-10-18 13:41:37.257
482945,42641add9346c864d4ea2124f1092275c590e28d,8415958,abcat0904005,keyless entry,2011-10-25 23:52:01.96,2011-10-25 23:49:22.066
1266218,ade4d3a3638d694d7d808e0f0d0e42ff1e65fc82,7323087,pcmcat138100050035,dvi cable,2011-10-25 22:56:03.617,2011-10-25 22:55:13.947